name: Run tests
description: Install a snap and run specified tests for it.
author: Snapcrafters
branding:
  icon: check
  color: orange

inputs:
  issue-number:
    description: "The issue number to post to"
    required: true
  test-status:
    description: "The output status of the tests."
    required: true

outputs:
  status:
    description: "Success or failure status of the tests."
    value: ${{ steps.tests.outputs.status }}


runs:
  using: composite
  steps:
    - name: Comment on call for testing issue with screenshots
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: ${{ inputs.issue-number }},
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `Automated testing ${{ steps.tests.outputs.status }}.

            Full logs are available at https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/job/${{ github.job_id }}
            `
          })
